name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore SimpleRecords.sln

      - name: Build SimpleRecords.Common
        run: |
          msbuild.exe SimpleRecords.Common/SimpleRecords.Common.csproj -t:"Clean;Build" /p:configuration="Release"

      - name: Build SimpleRecords.Common.Tests
        run: |
          msbuild.exe SimpleRecords.Common.Tests/SimpleRecords.Common.Tests.csproj -t:"Clean;Build" /p:configuration="Release"

      - name: Run SimpleRecords.Common Tests
        run: vstest.console.exe SimpleRecords.Common.Tests/bin/Release/SimpleRecords.Common.Tests.dll

      - name: Build SimpleRecords.ConsoleApp
        run: |
          msbuild.exe SimpleRecords.ConsoleApp/SimpleRecords.ConsoleApp.csproj -t:"Clean;Build" /p:configuration="Release"

      - name: Build SimpleRecords.ConsoleApp.Tests
        run: |
          msbuild.exe SimpleRecords.ConsoleApp.Tests/SimpleRecords.ConsoleApp.Tests.csproj -t:"Clean;Build" /p:configuration="Release"

      - name: Run SimpleRecords.ConsoleApp Tests
        run: vstest.console.exe SimpleRecords.ConsoleApp.Tests/bin/Release/SimpleRecords.ConsoleApp.Tests.dll

      - name: Build SimpleRecords.API
        run: |
          msbuild.exe SimpleRecords.API/SimpleRecords.API.csproj -t:"Clean;Build" /p:configuration="Release"

      - name: Build SimpleRecords.API.Tests
        run: |
          msbuild.exe SimpleRecords.API.Tests/SimpleRecords.API.Tests.csproj -t:"Clean;Build" /p:configuration="Release"

      - name: Run SimpleRecords.API Tests
        run: vstest.console.exe SimpleRecords.API.Tests/bin/Release/SimpleRecords.API.Tests.dll